In [4]:
#Q1

import numpy as np
import random
#a
print("=====(a)=====")
# 語法：np.random.randint(low, high, size)
A = np.random.randint(1,30,size=(3,3))
print(A)
#b
print("=====(b)=====")
# 語法 np.full(shape, fill_value)
B = np.full((3,3),2)
print(B)
#c
print("=====(c)=====")
# 語法：np.arange(start, stop).reshape(new_shape)
C = np.arange(1,13).reshape((2,6))
print(C)
#d
print("=====(d)=====")
print(A*B)
#e
print("=====(e)=====")
C = np.arange(1,7).reshape((3,2))
print(np.dot(A,C))
#f
print("=====(f)=====")
mean = np.mean(A)
print(mean)
#g
print("=====(g)=====")
max = A.max()
print(max)
#h
print("=====(h)=====")
std = np.std(A)
print(std)
#i
print("=====(i)=====")
# 語法：ndarray.flatten(order)
print(A.flatten(order="F"))
#j
print("=====(j)=====")
# 語法：np.max(array, axis=0)
print(A.max(axis=0))



=====(a)=====
[[20 25 14]
 [ 9 28 20]
 [19 15 27]]
=====(b)=====
[[2 2 2]
 [2 2 2]
 [2 2 2]]
=====(c)=====
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
=====(d)=====
[[40 50 28]
 [18 56 40]
 [38 30 54]]
=====(e)=====
[[165 224]
 [193 250]
 [199 260]]
=====(f)=====
19.666666666666668
=====(g)=====
28
=====(h)=====
5.962847939999439
=====(i)=====
[20  9 19 25 28 15 14 20 27]
=====(j)=====
[20 28 27]


In [20]:
#Q2
import numpy as np

#A
print("=====(A)=====")
# 語法：np.arange(start, stop) → stop 不包含在內
A = np.arange(3,13)
print(A)

#B
print("=====(B)=====")
B = np.arange(10,0,-1)
print(B)

#C
print("=====(C)=====")
A = A.reshape(2,5)
print(A)

#D
print("=====(D)=====")
B = B.reshape(5,2)
print(B)

#E
print("=====(E)=====")
#1 是"X"(水平)
# 語法：np.concatenate((a, b), axis=1) 進行水平合併
# 沿 axis=1（水平方向） 合併時，row 數（第 0 軸）需相等
E = np.concatenate((A,B.reshape(2,5)),axis=1)
print(E)

#F
print("=====(F)=====")
#0 是"Y"(垂直)，
# 沿 axis=0（垂直方向） 合併時，column 數（第 1 軸）需相等
F = np.concatenate((A.reshape(5,2),B),axis=0)
print(F)

#G
print("=====(G)=====")
# 語法：np.vsplit(array, num_or_sections)
G = np.vsplit(E,2)
print(G)

#H
print("=====(H)=====")
# 語法：np.hsplit(array, num_or_sections)
H = np.hsplit(F,2)
print(H)

#I
print("=====(i)=====")
A = A.flatten(order="C")
print(A)

#J
print("=====(J)=====")
B = B.flatten(order="F")
print(B)

=====(A)=====
[ 3  4  5  6  7  8  9 10 11 12]
=====(B)=====
[10  9  8  7  6  5  4  3  2  1]
=====(C)=====
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]
=====(D)=====
[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
=====(E)=====
[[ 3  4  5  6  7 10  9  8  7  6]
 [ 8  9 10 11 12  5  4  3  2  1]]
=====(F)=====
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
=====(G)=====
[array([[ 3,  4,  5,  6,  7, 10,  9,  8,  7,  6]]), array([[ 8,  9, 10, 11, 12,  5,  4,  3,  2,  1]])]
=====(H)=====
[array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]]), array([[ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [ 9],
       [ 7],
       [ 5],
       [ 3],
       [ 1]])]
=====(i)=====
[ 3  4  5  6  7  8  9 10 11 12]
=====(J)=====
[10  8  6  4  2  9  7  5  3  1]


In [ ]:
#Q3
import numpy as np
import random

# 語法：np.random.randint(low, high, size)
K = np.random.randint(1,101,size=100)

#a
print("=====(a)=====")
# 語法：np.median(array)
print(np.median(K))

#b
print("=====(b)=====")
# 語法：np.var(array)
print(np.var(K))

#c
print("=====(c)=====")
# 語法：np.argmax(array)
print(np.argmax(K))

#d
print("=====(d)=====")
# 語法：np.argmin(array)
print(np.argmin(K))

#e
print("=====(e)=====")
for i in range(len(K)):
    if K[i] > 35 and K[i] <= 90:        #data[i] 表示第 i 個元素的值
        print(i)

=====(a)=====
56.5
=====(b)=====
770.6004
=====(c)=====
15
=====(d)=====
25
=====(f)=====
1
2
3
5
6
7
9
10
16
17
18
21
22
26
27
29
30
32
35
36
37
39
41
42
44
45
46
47
48
49
51
54
55
57
58
60
62
63
65
67
69
71
72
73
76
78
80
82
83
84
87
89
91
92
93
94
95
96
97
