In [4]:
#Q1

import numpy as np
import random
#a
print("=====(a)=====")
# 語法：np.random.randint(low, high, size)
A = np.random.randint(1,30,size=(3,3))
print(A)
#b
print("=====(b)=====")
# 語法 np.full(shape, fill_value)
B = np.full((3,3),2)
print(B)
#c
print("=====(c)=====")
# 語法：np.arange(start, stop).reshape(new_shape)
C = np.arange(1,13).reshape((2,6))
print(C)
#d
print("=====(d)=====")
print(A*B)
#e
print("=====(e)=====")
C = np.arange(1,7).reshape((3,2))
print(np.dot(A,C))
#f
print("=====(f)=====")
mean = np.mean(A)
print(mean)
#g
print("=====(g)=====")
max = A.max()
print(max)
#


=====(a)=====
[[29  5  9]
 [14 20 16]
 [16  6 21]]
=====(b)=====
[[2 2 2]
 [2 2 2]
 [2 2 2]]
=====(c)=====
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
=====(d)=====
[[58 10 18]
 [28 40 32]
 [32 12 42]]
=====(e)=====
[[ 89 132]
 [154 204]
 [139 182]]
=====(f)=====
15.11111111111111
=====(g)=====
29
