In [ ]:
#Q1

import numpy as np
import random
#a
print("=====(a)=====")
# 語法：np.random.randint(low, high, size)
A = np.random.randint(1,10,size=(3,3))
print(A )
#b
print("=====(b)=====")
# 語法 np.full(shape, fill_value)
B = np.full((3,3),2)
print(B)
#c
print("=====(c)=====")
# 語法：np.arange(start, stop).reshape(new_shape)
C = np.arange(1,13).reshape((2,6))
print(C)
#d
print("=====(d)=====")
print(A*B)
#e
print("=====(e)=====")
C = np.arange(1,7).reshape((3,2))
print(np.dot(A,C))
#f
print("=====(f)=====")


=====(a)=====
[[3 4 7]
 [2 3 1]
 [4 3 7]]
=====(b)=====
[[2 2 2]
 [2 2 2]
 [2 2 2]]
=====(c)=====
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
=====(d)=====
[[ 6  8 14]
 [ 4  6  2]
 [ 8  6 14]]
=====(e)=====
[[50 64]
 [16 22]
 [48 62]]
